# Generated by Django 5.2.4 on 2025-08-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_text_message_content_rename_user_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='username',
        ),
    ]
